M48
; DRILL file {KiCad (6.0.2)} date fr. 01. april 2022 kl. 16.02 +0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-04-01T16:02:17+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.660
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X78.39Y-43.944
X84.17Y-43.944
T2
X62.23Y-40.64
X62.23Y-113.03
X106.68Y-40.64
X106.68Y-113.03
T0
M30
